### PR TITLE
Ready. Specs working. Fixes #3

### LINKED ISSUE #3: Unstutter - Modularize - Abstract class
As for other Cadmium modules, I propose to : 

- Unstutter `Cadmium::Classifier` (`Cadmium::Classifier::BayesClassifier` => `Cadmium::Classifier::Bayes`)
- Modularize (create a `Cadmium::Classifier` module)
- Abstract out pertinent properties and methods of the `Bayes` class to an abstract class `Base`

The abstract class will be useful as we implement other classifiers.

@watzon : if you're ok with this, I can make a PR

### PR DESCRIPTION
**Pull request by rmarronnier**
The `Cadmium::Classifier::Base` abstract class will grow as we add new classifiers and figure out which properties and methods can be shared.

### CODE REVIEW

**Comment by watzon** [comment]
Something that we need to figure out with the `Base` class is what is going to be the same between all the classifiers, or if there isn't really going to be any parallels. If that's the case then a `Base` abstract class isn't really necessary.

**Comment by rmarronnier** [comment]
You're absolutely right. Right now things are foggy in this area. I'm implementing the Viterbi algorithm and in the end the fog will dissipate and the `Base` class will reflect those changes. Like what has incrementally happened with the `AbstractSummarizer` class (which I should rename to `Base`).
I propose that we keep this `Classifier::Base` for now and if nothing can be shared between the `Bayes` and `Viterbi` classes, we get rid of it.

**Comment by rmarronnier** [comment]
Well to be frank the `tokenizer` variable will be shared between all classifiers so that's one common shared ground :-)

**Comment by watzon** [comment]
One common thing, but not enough to justify the use of an abstract class in my opinion. Now if they also have shared functionality that's a whole other thing. Particularly if they all have a `train` and `categorize` method. Or maybe we rename `categorize` to `classify`?

**Comment by rmarronnier** [comment]
`train`, I don't know yet, but they will all have a `categorize`/`classify`  method that will return a tag.
If you're not convinced, I totally get it and can remove the `Base` abstract class.
As I said things are still foggy for me and I can't articulate my case good enough so I'll stop right here with argumentating :-) You decide ;-)

**Comment by watzon** [comment]
Go ahead and add a `classify` abstract method and in the Bayes classifier change `categorize` -> `classify`. We can worry about training later once we have other classifiers.

**Comment by rmarronnier** [comment]
Great ! You won't regret this ;-)

**Pull request merged**
